### ISSUE TITLE
Can we not just reuse the array we have in src/optionList.json ? this duplication seems unnecessary as this object could be dynamically created rather than hardcoded

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/eos-icons-adobe-xd#12]
Can we not just reuse the array we have in src/optionList.json ? this duplication seems unnecessary as this object could be dynamically created rather than hardcoded

_Originally posted by @cyntss in https://github.com/EOS-uiux-Solutions/eos-icons-adobe-xd/pull/10#discussion_r671111968_

**Comment by Abhirup-99** [comment]
Fixed in #11.
