### ISSUE TITLE
Default Theme set to Outlined

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/eos-icons-adobe-xd#16]
Current State : 
The theme section in the adobe xd plugin is currently set to outlined, but the icons are default set to filled. When a user tries to search any icon the filled icon gets changed to outlined.

https://user-images.githubusercontent.com/67755381/158238212-3c9c00d9-e8ee-4518-b920-637071a6e7ea.mp4

Expected State : 
The theme section should contain default value for filled so that state may not change from filled to outline while searching.

**Comment by AnshumanDhiman** [comment]
I would like to work on this issue.

**Comment by Abhirup-99** [comment]
Closed by #24.
